openapi: 3.0.0
info:
  title: Full Order Flow API
  version: 1.0.0
servers:
  - url: /api/orders
paths:
  /cart/add:
    post:
      summary: Add item to cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
                quantity:
                  type: integer
      responses:
        '200':
          description: Cart updated
  /cart:
    get:
      summary: View cart
      responses:
        '200':
          description: Cart contents
  /cart/remove:
    post:
      summary: Remove item from cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: string
      responses:
        '200':
          description: Cart updated
  /place-order:
    post:
      summary: Place order from cart
      responses:
        '201':
          description: Order created
  /pay:
    post:
      summary: Pay for order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
      responses:
        '200':
          description: Payment successful
  /deliver:
    post:
      summary: Mark order as delivered
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
      responses:
        '200':
          description: Order delivered
